version: '3.8'

services:
  hackerground:
    image: acrtd2paiyvckrz2.azurecr.io/dongbao/uiseong-come-on:latest
    container_name: hackerground
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
