name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches:
      - backend

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          ./gradlew build -x test

      - name: Build Docker image
        run: |
          docker build -t dongbao/uiseong-come-on:latest .

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.AZURE_CREDENTIALS }} | docker login acrtd2paiyvckrz2.azurecr.io --username $(jq -r '.clientId' /tmp/azure_credentials.json) --password $(jq -r '.clientSecret' /tmp/azure_credentials.json)

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag dongbao/uiseong-come-on:latest acrtd2paiyvckrz2.azurecr.io/dongbao/uiseong-come-on:latest
          docker push acrtd2paiyvckrz2.azurecr.io/dongbao/uiseong-come-on:latest

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID }}
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"

      - name: Log in with Azure (Client Credentials)
        if: ${{ env.AZURE_CREDENTIALS }}
        run: |
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable
          Write-Host "::add-mask::$($info.clientSecret)"
          
          azd auth login 
            --client-id "$($info.clientId)" 
            --client-secret "$($info.clientSecret)" 
            --tenant-id "$($info.tenantId)"
        shell: pwsh
        env:
          AZURE_CREDENTIALS: ${{ env.AZURE_CREDENTIALS }}

      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}

      - name: Deploy Application
        run: azd deploy --no-prompt
