on:
  workflow_dispatch:
  push:
    branches:
      - backend

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      ACR_NAME: ${{ secrets.ACR_NAME }}  # Azure Container Registry 이름
      IMAGE_NAME: hackerground/hackerground-badexpectations

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          ./gradlew build -x test

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name acrtd2paiyvckrz2

      - name: Build and Push Docker Image
        run: |
          docker build -t acrtd2paiyvckrz2.azurecr.io/dongbao/uiseong-come-on:latest .
          docker push acrtd2paiyvckrz2.azurecr.io/dongbao/uiseong-come-on:latest

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
          --name ca-hackerground-hhn6znikr62lw  \
          --resource-group BadExpectations \
          --image acrtd2paiyvckrz2.azurecr.io/your-image-name:latest
